### ISSUE TITLE
[Bugs] 카린아 깃헙 명령어를 사용했을때의 증상

### ISSUE THREAD

**Issue by Egg0215** [Team-Reato/KRB-v2#1]
## 카린봇의 버그를 실행시키는 사진을 올려주세요!
* 개발자가 알기 쉽게 사진과 글을 첨부해주세요!
카린아 깃헙 입력시 뒤에 알수 없는 명령어 와 같은 내용이 뜸
사진X
## 카린봇의 버그를 해결한 뒤의 동작을 써주세요!
* 개발자가 알기 쉽게 글을 입력해주세요!
카린아 깃헙입력시 그냥 embed만 던져놓고 가야함
## 혹시 해당 버그로 인하여 문제가 된 것이 있으신가요?
* 무슨 문제가 발생하는지 이해하기 쉽게 글로 적어주세요.
X
## 유저의 커넥션 정보
* 컴퓨터 정보와 디스코드 버전 및 서버 버전을 알려주세요.

## 이슈를 올리기 전에 아래를 확인해주세요!
- [ ] 이전에 처리했거나 중복되는 이슈는 없나요?
- [ ] 해당 버그를 정상적인 방법으로 발생시킬 수 있나요?
* 위의 확인 작성중에 문제되는 것이 있다면 이슈를 진행하는 속도가 느려질 수 있습니다!

**Comment by KaRinKaRin876** [comment]
Fixed
